/// Flutter icons CardFonts
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CardFonts
///      fonts:
///       - asset: fonts/CardFonts.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class CardFonts {
  CardFonts._();

  static const _kFontFam = 'CardFonts';
  static const String? _kFontPkg = null;

  static const IconData clover = IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearts = IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spade = IconData(0xeaaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
